import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { DynamicContextProvider } from '@dynamic-labs/sdk-react-core';
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <DynamicContextProvider
                settings={{
                    environmentId: 'a5baebf3-dff6-4185-9fec-a40b14bae0e4',
                    walletConnectors: [EthereumWalletConnectors],
                }}>
                <body className={inter.className}>
                    {children}
                </body>
            </DynamicContextProvider>
        </html>
    )
}
